name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Roda em qualquer branch
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout do código no branch atual
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configurar o Python e instalar dependências
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Rodar os testes
    - name: Run tests with pytest
      run: |
        pytest -v

    # Step 4: Validar o estilo do código (opcional)
    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .
        pip install black
        black --check .
        flake8 .